# -*- coding: utf-8 -*-
"""mentalhealth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCEhn5Z3T62V3t6lDfX-2jLWWfvd2CNw
"""

# config.py
# Central location for all configuration settings

# File paths
DATA_PATH = 'Teen_Mental_Health.csv'
MODEL_PATH = 'depression_model.pkl'
SCALER_PATH = 'feature_scaler.pkl'
ENCODER_PATH = 'gender_encoder.pkl'

# Model parameters
RANDOM_STATE = 42
TEST_SIZE = 0.2
N_ESTIMATORS = 100
MAX_DEPTH = 10

# Feature lists
NUMERICAL_FEATURES = [
    'age', 'daily_social_media_hours', 'sleep_hours',
    'screen_time_before_sleep', 'academic_performance',
    'physical_activity'
]

CATEGORICAL_FEATURES = [
    'gender', 'platform_usage', 'digital_wellbeing_flag','social_interaction_level', 'sleep_quality'
]

ALL_FEATURES = NUMERICAL_FEATURES + [
    f'{col}_encoded' for col in CATEGORICAL_FEATURES
]

# Target column
TARGET_COLUMN = 'depression_label'

# utils.py
# Shared utility functions used across multiple files

import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import StandardScaler, LabelEncoder

def load_data(filepath):
    """Load dataset from CSV"""
    print(f"Loading data from {filepath}...")
    df = pd.read_csv(filepath)
    print(f"Loaded {df.shape[0]} rows, {df.shape[1]} columns")
    return df

def save_object(obj, filepath):
    """Save a Python object using joblib"""
    joblib.dump(obj, filepath)
    print(f"Saved to {filepath}")

def load_object(filepath):
    """Load a Python object using joblib"""
    return joblib.load(filepath)

def check_missing_values(df):
    """Check and report missing values"""
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if len(missing) > 0:
        print("\n⚠️ Missing values found:")
        for col, count in missing.items():
            print(f"  {col}: {count} ({count/len(df)*100:.1f}%)")
        return True
    else:
        print("✅ No missing values found")
        return False

def handle_missing_values(df):
    """Handle missing values based on column type"""
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype == 'object':
                df[col].fillna(df[col].mode()[0], inplace=True)
                print(f"  Filled {col} with mode: {df[col].mode()[0]}")
            else:
                df[col].fillna(df[col].median(), inplace=True)
                print(f"  Filled {col} with median: {df[col].median()}")
    return df

def check_class_balance(y):
    """Check if dataset is imbalanced"""
    balance = y.value_counts(normalize=True)
    min_class = balance.min()
    print(f"\nClass distribution:")
    print(balance)

    if min_class < 0.2:
        print(f"⚠️ Imbalanced dataset detected (minority class: {min_class:.1%})")
        return True
    else:
        print("✅ Dataset is balanced")
        return False

# 01_data_preprocessing.py
# Step 1: Load and clean the raw data

import pandas as pd
import sys
from config import DATA_PATH
from utils import load_data, check_missing_values, handle_missing_values

def main():
    print("="*60)
    print("STEP 1: DATA PREPROCESSING")
    print("="*60)

    # Load data
    df = load_data(DATA_PATH)

    # Check for missing values
    has_missing = check_missing_values(df)
    if has_missing:
        print("\nHandling missing values...")
        df = handle_missing_values(df)

    # Remove duplicates if any
    initial_rows = len(df)
    df = df.drop_duplicates()
    if len(df) < initial_rows:
        print(f"Removed {initial_rows - len(df)} duplicate rows")

    # Check data types
    print("\nData types:")
    for col in df.columns:
        print(f"  {col}: {df[col].dtype}")

    # Save cleaned data
    cleaned_path = 'data_cleaned.csv'
    df.to_csv(cleaned_path, index=False)
    print(f"\n✅ Cleaned data saved to {cleaned_path}")

    return df

if __name__ == "__main__":
    df = main()

# 02_feature_engineering.py
# Step 2: Encode categorical variables and create features

import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
import joblib
# The next import will be overridden locally due to potential caching issues
from config import NUMERICAL_FEATURES, CATEGORICAL_FEATURES, TARGET_COLUMN
from utils import save_object, check_class_balance

def main():
    print("="*60)
    print("STEP 2: FEATURE ENGINEERING")
    print("="*60)

    # Explicitly define corrected feature lists within this function
    # to ensure the latest definitions are used, overriding any cached imports.
    corrected_numerical_features = [
        'age', 'daily_social_media_hours', 'sleep_hours',
        'screen_time_before_sleep', 'academic_performance',
        'physical_activity'
    ]

    corrected_categorical_features = [
        'gender', 'platform_usage', 'digital_wellbeing_flag',
        'social_interaction_level', 'sleep_quality'
    ]

    # Load cleaned data
    df = pd.read_csv('data_cleaned.csv')
    print(f"Loaded {len(df)} rows")

    # Check target variable
    print(f"\nTarget column: {TARGET_COLUMN}")
    print(f"Unique values: {df[TARGET_COLUMN].unique()}")

    # Encode target if needed
    if df[TARGET_COLUMN].dtype == 'object':
        print("\nEncoding target variable...")
        le_target = LabelEncoder()
        df['depression_label_encoded'] = le_target.fit_transform(df[TARGET_COLUMN])
        y = df['depression_label_encoded']
        save_object(le_target, 'target_encoder.pkl')
        print(f"Mapping: {dict(zip(le_target.classes_, le_target.transform(le_target.classes_)))}")
    else:
        y = df[TARGET_COLUMN]

    # Check class balance
    check_class_balance(y)

    # Encode categorical features using the corrected list
    encoders = {}
    for cat_col in corrected_categorical_features:
        print(f"\nEncoding {cat_col}...")
        le = LabelEncoder()
        df[f'{cat_col}_encoded'] = le.fit_transform(df[cat_col])
        encoders[cat_col] = le
        # Fix: Added a closing parenthesis and curly brace for the f-string
        print(f"  Unique values: {dict(zip(le.classes_, le.transform(le.classes_)))}")
        save_object(le, f'{cat_col}_encoder.pkl')

    # Prepare feature matrix using the corrected lists
    X = df[[f'{col}_encoded' if col in corrected_categorical_features else col
            for col in corrected_numerical_features + corrected_categorical_features]]

    # Rename columns for consistency
    X.columns = corrected_numerical_features + [f'{col}_encoded' for col in corrected_categorical_features]

    print(f"\nFeature matrix shape: {X.shape}")
    print(f"Features: {X.columns.tolist()}")

    # Scale numerical features using the corrected list
    print("\nScaling numerical features...")
    scaler = StandardScaler()
    X[corrected_numerical_features] = scaler.fit_transform(X[corrected_numerical_features])
    save_object(scaler, 'scaler.pkl')
    print("✅ Scaling complete")

    # Save processed data
    processed_data = pd.concat([X, y], axis=1)
    processed_data.to_csv('data_processed.csv', index=False)
    print(f"\n✅ Processed data saved to data_processed.csv")

    return X, y

if __name__ == "__main__":
    X, y = main()

# 03_train_depression_model.py
# Step 3: Train the depression prediction model

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from config import TEST_SIZE, RANDOM_STATE, N_ESTIMATORS, MAX_DEPTH, TARGET_COLUMN
from utils import save_object

def main():
    print("="*60)
    print("STEP 3: TRAINING DEPRESSION MODEL")
    print("="*60)

    # Load processed data
    df = pd.read_csv('data_processed.csv')

    # Separate features and target
    # Corrected: Use TARGET_COLUMN as it was not encoded into 'depression_label_encoded'
    X = df.drop(TARGET_COLUMN, axis=1)
    y = df[TARGET_COLUMN]

    print(f"Features: {X.columns.tolist()}")
    print(f"Target distribution:\n{y.value_counts(normalize=True)}")

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )

    print(f"\nTraining set: {len(X_train)} samples")
    print(f"Test set: {len(X_test)} samples")
    print(f"Training depression rate: {y_train.mean():.1%}")
    print(f"Test depression rate: {y_test.mean():.1%}")

    # Train model
    print("\nTraining Random Forest classifier...")
    model = RandomForestClassifier(
        n_estimators=N_ESTIMATORS,
        max_depth=MAX_DEPTH,
        class_weight='balanced',
        random_state=RANDOM_STATE,
        n_jobs=-1
    )

    model.fit(X_train, y_train)
    print("✅ Training complete")

    # Quick evaluation on test set
    y_pred_proba = model.predict_proba(X_test)[:, 1]
    auc = roc_auc_score(y_test, y_pred_proba)
    print(f"\n📊 Test ROC-AUC: {auc:.3f}")

    # Save model
    save_object(model, 'depression_model.pkl')

    # Save feature names for later use
    feature_names = X.columns.tolist()
    save_object(feature_names, 'feature_names.pkl')

    # Feature importance
    importance_df = pd.DataFrame({
        'feature': feature_names,
        'importance': model.feature_importances_
    }).sort_values('importance', ascending=False)

    print("\n📈 TOP 10 IMPORTANT FEATURES:")
    print(importance_df.head(10).to_string(index=False))

    # Save feature importance
    importance_df.to_csv('feature_importance.csv', index=False)

    return model, X_test, y_test

if __name__ == "__main__":
    model, X_test, y_test = main()

# 04_evaluate_model.py
# Step 4: Evaluate model performance

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (classification_report, confusion_matrix,
                            roc_curve, roc_auc_score, precision_recall_curve)
from utils import load_object
from config import TARGET_COLUMN # Import TARGET_COLUMN

def main():
    print("="*60)
    print("STEP 4: MODEL EVALUATION")
    print("="*60)

    # Load model and data
    model = load_object('depression_model.pkl')
    df = pd.read_csv('data_processed.csv')
    feature_names = load_object('feature_names.pkl')

    # Prepare test data (using same split as training)
    from sklearn.model_selection import train_test_split
    from config import TEST_SIZE, RANDOM_STATE

    X = df[feature_names]
    # Fix: Use TARGET_COLUMN instead of 'depression_label_encoded'
    y = df[TARGET_COLUMN]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )

    # Predictions
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]

    # Metrics
    auc = roc_auc_score(y_test, y_pred_proba)
    print(f"\n🎯 ROC-AUC Score: {auc:.3f}")

    print("\n📋 CLASSIFICATION REPORT:")
    print(classification_report(y_test, y_pred, target_names=['No Depression', 'Depression']))

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()

    print("\n📊 CONFUSION MATRIX:")
    print("                 Predicted")
    print("                 No Dep  Dep")
    print(f"Actual No Dep:    {tn:4d}   {fp:4d}")
    print(f"Actual Dep:       {fn:4d}   {tp:4d}")

    # Additional metrics
    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)
    precision = tp / (tp + fp)
    f1 = 2 * (precision * sensitivity) / (precision + sensitivity)

    print(f"\n📈 DETAILED METRICS:")
    print(f"  Sensitivity (Recall): {sensitivity:.3f} - % depressed correctly identified")
    print(f"  Specificity: {specificity:.3f} - % non-depressed correctly identified")
    print(f"  Precision: {precision:.3f} - % of depression predictions that were correct")
    print(f"  F1-Score: {f1:.3f} - Harmonic mean of precision & recall")

    # Visualizations
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))

    # 1. Confusion Matrix Heatmap
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0,0])
    axes[0,0].set_title('Confusion Matrix')
    axes[0,0].set_xlabel('Predicted')
    axes[0,0].set_ylabel('Actual')
    axes[0,0].set_xticklabels(['No Dep', 'Dep'])
    axes[0,0].set_yticklabels(['No Dep', 'Dep'])

    # 2. ROC Curve
    fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
    axes[0,1].plot(fpr, tpr, 'b-', linewidth=2, label=f'AUC = {auc:.3f}')
    axes[0,1].plot([0, 1], [0, 1], 'r--', label='Random')
    axes[0,1].set_xlabel('False Positive Rate')
    axes[0,1].set_ylabel('True Positive Rate')
    axes[0,1].set_title('ROC Curve')
    axes[0,1].legend()
    axes[0,1].grid(True, alpha=0.3)

    # 3. Precision-Recall Curve
    precision_vals, recall_vals, _ = precision_recall_curve(y_test, y_pred_proba)
    axes[1,0].plot(recall_vals, precision_vals, 'g-', linewidth=2)
    axes[1,0].set_xlabel('Recall')
    axes[1,0].set_ylabel('Precision')
    axes[1,0].set_title('Precision-Recall Curve')
    axes[1,0].grid(True, alpha=0.3)

    # 4. Probability Distribution
    axes[1,1].hist(y_pred_proba[y_test==0], bins=20, alpha=0.7, label='No Depression', color='green')
    axes[1,1].hist(y_pred_proba[y_test==1], bins=20, alpha=0.7, label='Depression', color='red')
    axes[1,1].set_xlabel('Predicted Probability of Depression')
    axes[1,1].set_ylabel('Count')
    axes[1,1].set_title('Prediction Probability Distribution')
    axes[1,1].legend()

    plt.tight_layout()
    plt.savefig('evaluation_plots.png', dpi=150)
    plt.show()

    print("\n✅ Evaluation plots saved to 'evaluation_plots.png'")

    # Save metrics to file
    metrics_df = pd.DataFrame({
        'Metric': ['ROC-AUC', 'Sensitivity', 'Specificity', 'Precision', 'F1-Score'],
        'Value': [auc, sensitivity, specificity, precision, f1]
    })
    metrics_df.to_csv('model_metrics.csv', index=False)
    print("✅ Metrics saved to 'model_metrics.csv'")

if __name__ == "__main__":
    main()

import pandas as pd
import numpy as np
from utils import load_object
import config # Import config module directly
import importlib # For reloading config

class DepressionPredictor:
    def __init__(self):
        """Load all saved models and encoders"""
        print("Loading model and encoders...")

        # Reload config to ensure we get the latest definitions
        importlib.reload(config)
        # Explicitly define feature lists within this class
        # to ensure the latest definitions are used, overriding any cached imports.
        # This mirrors the approach in 02_feature_engineering.py which successfully handled config updates.
        self.NUMERICAL_FEATURES = [
            'age', 'daily_social_media_hours', 'sleep_hours',
            'screen_time_before_sleep', 'academic_performance',
            'physical_activity'
        ]

        self.CATEGORICAL_FEATURES = [
            'gender', 'platform_usage', 'digital_wellbeing_flag',
            'social_interaction_level', 'sleep_quality'
        ]

        self.model = load_object('depression_model.pkl')
        self.scaler = load_object('scaler.pkl')
        self.feature_names = load_object('feature_names.pkl')

        # Load encoders for categorical features
        self.encoders = {}
        for cat_col in self.CATEGORICAL_FEATURES:
            self.encoders[cat_col] = load_object(f'{cat_col}_encoder.pkl')

        print("✅ Ready to make predictions")

    def preprocess_input(self, data_dict):
        """
        Convert raw input dictionary to model-ready format

        Expected format:
        {
            'age': 25,
            'gender': 'Male',
            'daily_social_media_hours': 6,
            'platform_usage': 'Instagram',
            'sleep_hours': 5,
            'screen_time_before_sleep': 2,
            'academic_performance': 3,
            'physical_activity': 2,
            'social_interaction_level': 2,
            'sleep_quality': 3,
            'digital_wellbeing_flag': 'No'
        }
        """
        # Create dataframe
        df = pd.DataFrame([data_dict])

        # Encode categorical features
        for cat_col in self.CATEGORICAL_FEATURES:
            encoder = self.encoders[cat_col]
            input_value = str(df[cat_col].iloc[0])
            # Conditionally convert to lowercase based on how the encoder was trained
            if cat_col in ['gender', 'social_interaction_level']:
                input_value = input_value.lower()

            encoded_value = encoder.transform([input_value])[0]
            df[f'{cat_col}_encoded'] = encoded_value

        # Select features in correct order
        feature_values = []
        for feature in self.feature_names:
            if feature in self.NUMERICAL_FEATURES:
                feature_values.append(df[feature].iloc[0])
            else:  # Encoded feature
                feature_values.append(df[feature].iloc[0])

        # Scale numerical features
        X = np.array(feature_values).reshape(1, -1)
        numerical_indices = [i for i, f in enumerate(self.feature_names)
                            if f in self.NUMERICAL_FEATURES]

        # Ensure we're only scaling the numerical parts of X
        # X is a 2D array, so slicing needs to be careful
        numerical_data_to_scale = X[:, numerical_indices]
        X[:, numerical_indices] = self.scaler.transform(numerical_data_to_scale)

        return X

    def predict(self, data_dict):
        """Make prediction for a single person"""
        X = self.preprocess_input(data_dict)

        # Get prediction
        prediction = self.model.predict(X)[0]
        probability = self.model.predict_proba(X)[0][1]

        return {
            'depression': bool(prediction),
            'probability': float(probability),
            'risk_level': self._get_risk_level(probability)
        }

    def predict_batch(self, data_list):
        """Make predictions for multiple people"""
        results = []
        for data in data_list:
            results.append(self.predict(data))
        return results

    def _get_risk_level(self, probability):
        """Convert probability to risk level"""
        if probability >= 0.7:
            return "High Risk"
        elif probability >= 0.4:
            return "Moderate Risk"
        else:
            return "Low Risk"

def main():
    print("="*60)
    print("STEP 5: MAKE PREDICTIONS")
    print("="*60)

    # Initialize predictor
    predictor = DepressionPredictor()

    # Example 1: Single prediction
    print("\n--- Single Prediction Example ---")
    sample_person = {
        'age': 25,
        'gender': 'Male', # This will be converted to 'male' before encoding
        'daily_social_media_hours': 6,
        'platform_usage': 'Instagram',
        'sleep_hours': 5,
        'screen_time_before_sleep': 2,
        'academic_performance': 3,
        'physical_activity': 2,
        'social_interaction_level': 'medium', # Adjusted to match expected categories
        'sleep_quality': 'Fair', # Adjusted to match expected categories
        'digital_wellbeing_flag': 'Healthy' # Adjusted to match expected categories
    }

    result = predictor.predict(sample_person)

    print("\nInput Data:")
    for key, value in sample_person.items():
        print(f"  {key}: {value}")

    print("\nPrediction Result:")
    print(f"  Depression: {'Yes' if result['depression'] else 'No'}")
    print(f"  Probability: {result['probability']:.1%}")
    print(f"  Risk Level: {result['risk_level']}")

    # Example 2: Batch prediction
    print("\n--- Batch Prediction Example ---")
    batch_data = [
        {
            'age': 30,
            'gender': 'Female',
            'daily_social_media_hours': 2,
            'platform_usage': 'Facebook',
            'sleep_hours': 8,
            'screen_time_before_sleep': 0.5,
            'academic_performance': 4,
            'physical_activity': 4,
            'social_interaction_level': 'high',
            'sleep_quality': 'Good',
            'digital_wellbeing_flag': 'Healthy'
        },
        {
            'age': 19,
            'gender': 'Female',
            'daily_social_media_hours': 8,
            'platform_usage': 'TikTok',
            'sleep_hours': 4,
            'screen_time_before_sleep': 3,
            'academic_performance': 2,
            'physical_activity': 1,
            'social_interaction_level': 'low',
            'sleep_quality': 'Poor',
            'digital_wellbeing_flag': 'At Risk'
        }
    ]

    batch_results = predictor.predict_batch(batch_data)

    for i, (person, result) in enumerate(zip(batch_data, batch_results), 1):
        print(f"\nPerson {i}:")
        print(f"  Social Media Hours: {person['daily_social_media_hours']}")
        print(f"  Sleep Hours: {person['sleep_hours']}")
        print(f"  Depression Risk: {result['probability']:.1%} ({result['risk_level']})")

if __name__ == "__main__":
    main()